# Generated by Django 4.0.2 on 2022-04-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('crop_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='crops')),
                ('season', models.CharField(default=None, max_length=100, verbose_name='Season')),
                ('climate', models.CharField(default=None, max_length=100, verbose_name='Climate')),
                ('soil', models.CharField(default=None, max_length=100, verbose_name='Soil')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('fert_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='fertilizer')),
            ],
        ),
        migrations.CreateModel(
            name='Irrigation',
            fields=[
                ('irri_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='irrigation')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('pest_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('Fungicide', 'Fungicide'), ('Insecticide', 'Insecticide'), ('Herbicide', 'Herbicide'), ('Nematicide', 'Nematicide'), ('Rodenticide', 'Rodenticide'), ('Acaricide', 'Acaricide'), ('Molluscicide', 'Molluscicide'), ('Bactericide', 'Bactericide'), ('Algalicide', 'Algalicide'), ('Avicide', 'Avicide')], max_length=100)),
                ('image', models.ImageField(upload_to='pesticide')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('gov_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Scheme Name')),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('sem_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('conducted_by', models.CharField(max_length=100)),
            ],
        ),
    ]
