# Generated by Django 4.0.2 on 2022-04-06 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('lab_res_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('result', models.TextField(max_length=1000, verbose_name='Result Description')),
                ('file', models.FileField(blank=True, null=True, upload_to='lab_result', verbose_name='File')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lab_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.labappointment')),
            ],
        ),
    ]
